import { MenuItem } from '../types/menu';

export const DEFAULT_MENUS: MenuItem[] = [
  // =================== 한식 (Korean - 25종) ===================
  {
    id: 'k1',
    name: '제육볶음',
    category: 'korean',
    description: '매콤달콤 불향 가득한 대한민국 직장인의 영원한 소울푸드',
    doroQuote: '제육에 상추쌈 싸 먹으면 도로롱도 밥 두 공기 뚝딱이다 도로롱!',
    tags: ['고기', '매콤', '인기', '가성비'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k2',
    name: '돼지김치찌개',
    category: 'korean',
    description: '돼지고기 듬뿍 넣고 푹 끓여낸 칼칼하고 진한 김치찌개',
    doroQuote: '국물 한 숟가락에 계란말이 곁들이면 극락이다 도로롱!',
    tags: ['국물', '얼큰', '칼칼', '찌개'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k3',
    name: '차돌 / 우렁 된장찌개',
    category: 'korean',
    description: '구수한 집된장에 차돌박이와 두부가 듬뿍 들어간 뚝배기',
    doroQuote: '구수한 된장찌개에 밥 비벼 먹으면 속이 편안하다 도로롱.',
    tags: ['국물', '구수', '건강', '찌개'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k4',
    name: '순대국밥 / 돼지국밥',
    category: 'korean',
    description: '뽀얗고 진한 사골 육수에 다대기와 부추를 팍팍 넣은 국밥',
    doroQuote: '뜨끈한 국밥 든든하게 들이켜고 깡통 채우라 도로롱!',
    tags: ['국물', '해장', '뜨끈', '국밥'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k5',
    name: '뼈해장국 / 감자탕',
    category: 'korean',
    description: '살코기 두툼한 등뼈와 우거지가 어우러진 진국 해장국',
    doroQuote: '겨자 소스에 고기 콕 찍어먹고 밥 말아먹으라 도로롱!',
    tags: ['국물', '해장', '얼큰', '고기', '국밥'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k6',
    name: '콩나물국밥',
    category: 'korean',
    description: '수란과 오징어 젓갈을 곁들여 먹는 맑고 시원한 전주식 국밥',
    doroQuote: '어제 술독에 빠졌냐 도로롱? 콩나물국밥으로 속 풀라 도로롱!',
    tags: ['국물', '해장', '깔끔', '국밥'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k7',
    name: '의정부 / 송탄 부대찌개',
    category: 'korean',
    description: '스팸, 소시지, 민찌, 베이크드빈스에 라면사리 퐁당',
    doroQuote: '라면사리 불기 전에 먼저 건져먹어야 한다 도로롱!',
    tags: ['찌개', '얼큰', '푸짐', '헤비'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k8',
    name: '뚝배기 소불고기 (뚝불)',
    category: 'korean',
    description: '달달하고 짭조름한 양념에 팽이버섯과 당면이 호로록',
    doroQuote: '달달한 국물에 밥 쓱쓱 비벼 먹으면 꿀맛이다 도로롱!',
    tags: ['고기', '달달', '든든'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k9',
    name: '매콤 닭볶음탕',
    category: 'korean',
    description: '포슬포슬 감자와 매콤 칼칼하게 조려낸 닭도리탕',
    doroQuote: '양념 잘 밴 감자 으깨서 밥이랑 비벼 먹으라 도로롱!',
    tags: ['닭고기', '매콤', '든든'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'k10',
    name: '진한 육개장',
    category: 'korean',
    description: '대파와 양지고기, 토란대가 듬뿍 들어간 얼큰 붉은 보양 국물',
    doroQuote: '땀 뻘뻘 흘리면서 완뚝하면 감기 뚝 떨어진다 도로롱!',
    tags: ['국물', '얼큰', '해장'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'k11',
    name: '삼겹살 / 목살 구이',
    category: 'korean',
    description: '불판에 지글지글 노릇하게 구운 통삼겹과 마늘, 구운 김치',
    doroQuote: '기름진 고기 냄새 맡으면 도로롱도 눈 돌아간다 도로롱!',
    tags: ['고기', '구이', '헤비'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k12',
    name: '보쌈 & 무말랭이 정식',
    category: 'korean',
    description: '잡내 없이 야들야들하게 삶아낸 돼지고기 수육과 아삭 김치',
    doroQuote: '새우젓 살짝 찍고 알배추에 싸 먹으면 예술이다 도로롱!',
    tags: ['고기', '백반', '든든'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k13',
    name: '노릇노릇 생선구이 백반',
    category: 'korean',
    description: '겉바속촉 짭조름하게 구워낸 고등어/삼치/임연수 구이 정식',
    doroQuote: '와사비 간장에 생선살 콕 찍어서 흰쌀밥이랑 먹으라 도로롱.',
    tags: ['생선', '담백', '백반'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'k14',
    name: '오징어 / 낙지 볶음',
    category: 'korean',
    description: '탱글탱글 쫄깃한 식감에 매콤한 불향 양념이 입맛 돋우는 볶음',
    doroQuote: '콩나물이랑 김가루 넣고 쓱쓱 비벼 먹으라 도로롱!',
    tags: ['해산물', '매콤', '불향'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'k15',
    name: '바지락 / 닭 칼국수',
    category: 'korean',
    description: '시원하고 뽀얀 국물에 쫄깃한 손칼국수 면발과 겉절이 김치',
    doroQuote: '칼국수 집은 겉절이가 생명이다 도로롱! 세 번 리필하라 도로롱!',
    tags: ['면류', '국물', '뜨끈'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'k16',
    name: '얼큰 수제비 / 칼제비',
    category: 'korean',
    description: '손으로 얇게 뜯어 넣은 쫄깃한 반죽과 칼칼한 장칼국수 국물',
    doroQuote: '비 오는 날엔 무조건 수제비 한 그릇 땡겨야 한다 도로롱!',
    tags: ['면류', '국물', '얼큰'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k17',
    name: '돌솥 비빔밥',
    category: 'korean',
    description: '지글지글 소리 내며 밑바닥 누룽지가 바삭하게 눌어붙는 비빔밥',
    doroQuote: '참기름 한 바퀴 쓱 두르고 누룽지 긁어먹으라 도로롱!',
    tags: ['밥류', '나물', '건강'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'k18',
    name: '안동 찜닭',
    category: 'korean',
    description: '단짠 간장 소스에 푹 익힌 닭고기와 납작당면, 감자의 조화',
    doroQuote: '납작당면 호로록 건져먹고 남은 국물에 밥 비비라 도로롱!',
    tags: ['닭고기', '단짠', '푸짐'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k19',
    name: '매운 소갈비찜 / 돼지갈비찜',
    category: 'korean',
    description: '뼈에서 살이 쏙쏙 분리되는 부드러운 육질의 갈비찜',
    doroQuote: '오늘은 특별한 날이냐 도로롱? 고기 뜯고 힘내라 도로롱!',
    tags: ['고기', '고급', '매콤'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'k20',
    name: '구수한 청국장 찌개',
    category: 'korean',
    description: '콩 알갱이가 살아있는 진하고 구수한 고향의 맛 청국장',
    doroQuote: '냄새는 구수하지만 한 입 먹으면 밥도둑이다 도로롱!',
    tags: ['찌개', '구수', '건강'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k21',
    name: '살얼음 물냉면 / 비빔냉면',
    category: 'korean',
    description: '동치미 육수의 시원한 물냉면 또는 매콤달콤 양념 비빔냉면',
    doroQuote: '식초 겨자 팍팍 치고 가위질 두 번 싹둑 하라 도로롱!',
    tags: ['면류', '시원', '깔끔'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'k22',
    name: '춘천 닭갈비 & 볶음밥',
    category: 'korean',
    description: '넓은 철판에 양배추, 고구마, 떡과 함께 볶는 매콤 닭갈비',
    doroQuote: '치즈 사리 추가하고 마지막엔 무조건 볶음밥이다 도로롱!',
    tags: ['닭고기', '철판', '매콤'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'k23',
    name: '도토리 묵사발 / 묵밥',
    category: 'korean',
    description: '살얼음 육수에 탱글탱글 도토리묵과 김치, 김가루를 얹은 별미',
    doroQuote: '더위 먹었거나 입맛 없을 땐 시원한 묵밥이 보약이다 도로롱.',
    tags: ['시원', '가벼운', '별미'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'k24',
    name: '황태 / 북엇국',
    category: 'korean',
    description: '들기름에 볶아 뽀얗게 우려낸 황태포와 부드러운 두부, 계란',
    doroQuote: '쓰린 속을 어루만져 주는 가장 부드러운 해장국이다 도로롱.',
    tags: ['국물', '해장', '담백'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'k25',
    name: '잔치국수 & 김치전',
    category: 'korean',
    description: '멸치 다시마 육수에 소면 말아 올리고 바삭한 김치전 곁들이기',
    doroQuote: '후루룩 넘어가는 국수와 바삭한 전의 조합은 필승이다 도로롱!',
    tags: ['면류', '가성비', '간편'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },

  // =================== 일식 (Japanese - 15종) ===================
  {
    id: 'j1',
    name: '두툼 돈카츠 (등심/안심)',
    category: 'japanese',
    description: '핑크빛 육즙이 가득한 두툼한 카츠와 바삭한 빵가루 튀김',
    doroQuote: '소금이랑 와사비 살짝 얹어서 바삭 베어물라 도로롱!',
    tags: ['튀김', '고기', '인기'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'j2',
    name: '돈코츠 / 미소 라멘',
    category: 'japanese',
    description: '진한 돈사골 육수에 불향 차슈와 아지타마고(반숙란) 토핑',
    doroQuote: '면발을 면치기해서 국물까지 싹 비우라 도로롱!',
    tags: ['면류', '국물', '라멘'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'j3',
    name: '모둠 초밥 (스시)',
    category: 'japanese',
    description: '신선한 광어, 연어, 참치, 새우 등이 정갈하게 나오는 모둠초밥',
    doroQuote: '오늘 지갑 사정이 넉넉하냐 도로롱? 나도 한 점만 달라 도로롱!',
    tags: ['해산물', '스시', '초밥', '깔끔'],
    specialDoroEmotion: 'sushi',
    enabled: true,
  },
  {
    id: 'j4',
    name: '생연어 덮밥 (사케동)',
    category: 'japanese',
    description: '고소한 기름기 도는 생연어 슬라이스와 생와사비 간장 덮밥',
    doroQuote: '연어의 부드러움에 도로롱도 사르르 녹아내린다 도로롱.',
    tags: ['덮밥', '해산물', '스시', '깔끔'],
    specialDoroEmotion: 'sushi',
    enabled: true,
  },
  {
    id: 'j5',
    name: '바삭 텐동 (모둠 튀김덮밥)',
    category: 'japanese',
    description: '새우, 온천계란, 김, 단호박 튀김에 달콤짭짤 타레 소스',
    doroQuote: '온천계란 톡 터뜨려 밥 비벼 먹으면 극락이다 도로롱!',
    tags: ['튀김', '덮밥', '바삭'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'j6',
    name: '소고기 덮밥 (규동)',
    category: 'japanese',
    description: '얇게 썬 우삼겹을 달콤짭조름한 양파 간장에 졸인 일식 덮밥',
    doroQuote: '초생강이랑 시치미 톡톡 뿌려 먹으면 꿀맛이다 도로롱.',
    tags: ['덮밥', '고기', '간편'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'j7',
    name: '가츠동 (돈까스 덮밥)',
    category: 'japanese',
    description: '바삭한 돈까스 위에 부드러운 달걀물을 촉촉하게 입힌 덮밥',
    doroQuote: '단짠 소스 머금은 돈까스와 밥의 든든한 한 그릇이다 도로롱!',
    tags: ['덮밥', '고기', '든든'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'j8',
    name: '판모밀 / 냉소바',
    category: 'japanese',
    description: '살얼음 띄운 쯔유에 간 무와 와사비 풀고 면 적셔 먹기',
    doroQuote: '머리끝까지 띵해지는 시원함으로 더위 사냥하라 도로롱!',
    tags: ['면류', '시원', '깔끔'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'j9',
    name: '일식 카레라이스',
    category: 'japanese',
    description: '양파를 카라멜라이징하여 깊은 풍미를 낸 진한 일본식 카레',
    doroQuote: '치킨가라아게나 소시지 토핑 얹어 먹으라 도로롱!',
    tags: ['밥류', '카레', '진한'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'j10',
    name: '마제소바 (비빔라멘)',
    category: 'japanese',
    description: '민찌 고기, 부추, 대파, 마늘, 계란 노른자를 비벼먹는 비빔면',
    doroQuote: '다시마 식초 중간에 뿌리고 마지막엔 밥 비벼먹어라 도로롱!',
    tags: ['면류', '감칠맛', '별미'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'j11',
    name: '활어 회덮밥',
    category: 'japanese',
    description: '신선한 회와 아삭한 채소 위에 새콤달콤 초고추장 쓱쓱',
    doroQuote: '초장 듬뿍 뿌려서 아삭하게 비벼 먹으라 도로롱!',
    tags: ['해산물', '스시', '새콤'],
    specialDoroEmotion: 'sushi',
    enabled: true,
  },
  {
    id: 'j12',
    name: '장어 덮밥 (우나기동)',
    category: 'japanese',
    description: '특제 데리야끼 소스를 발라 숯불에 구워낸 보양 장어구이 덮밥',
    doroQuote: '스태미나 충전 완료! 오늘 야근도 끄떡없다 도로롱!',
    tags: ['보양', '고급', '덮밥'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'j13',
    name: '스키야키 / 샤브샤브',
    category: 'japanese',
    description: '달콤한 간장 육수에 얇은 소고기와 배추, 버섯을 날달걀에 콕',
    doroQuote: '생달걀에 푹 찍어 먹으면 부드러움의 극치다 도로롱!',
    tags: ['국물', '고기', '따뜻'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'j14',
    name: '사누끼 우동 & 튀김',
    category: 'japanese',
    description: '탱글탱글 쫄깃한 면발과 깔끔한 가쓰오부시 국물의 온우동',
    doroQuote: '면발이 목구멍을 부드럽게 타고 넘어간다 도로롱!',
    tags: ['면류', '국물', '따뜻'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'j15',
    name: '오코노미야키 & 타코야키',
    category: 'japanese',
    description: '양배추와 해물 부침 위에 춤추는 가쓰오부시와 마요네즈',
    doroQuote: '시원한 맥주 한 잔 곁들이면 완벽한 조합이다 도로롱!',
    tags: ['별미', '단짠', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },

  // =================== 중식 (Chinese - 15종) ===================
  {
    id: 'c1',
    name: '짜장면 & 찹쌀탕수육',
    category: 'chinese',
    description: '달콤고소 춘장 소스 비벼서 바삭 쫄깃한 탕수육과 함께',
    doroQuote: '짜장면은 단무지 감싸서 후루룩 면치기하라 도로롱!',
    tags: ['면류', '단짠', '인기'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'c2',
    name: '얼큰 해물 짬뽕',
    category: 'chinese',
    description: '불향 가득 채소와 신선한 홍합, 오징어가 뿜어내는 얼큰 국물',
    doroQuote: '어제 술 마셨냐 도로롱? 짬뽕 국물로 속 뻥 뚫으라 도로롱!',
    tags: ['면류', '국물', '얼큰', '해장'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'c3',
    name: '간짜장 & 계란후라이',
    category: 'chinese',
    description: '양파가 아삭하게 살아있는 갓 볶은 진한 춘장 소스',
    doroQuote: '계란 노른자 톡 터뜨려 비비면 고소함 폭발이다 도로롱!',
    tags: ['면류', '불향', '단짠'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'c4',
    name: '마라탕 / 마라샹궈',
    category: 'chinese',
    description: '얼얼한 마라 소스와 내가 직접 담은 신선한 재료의 조화',
    doroQuote: '옥수수면이랑 푸주, 소고기 듬뿍 넣어라 도로롱! 불뿜는다 도로롱!',
    tags: ['매운', '마라', '중독', '얼큰'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'c5',
    name: '중화 볶음밥 & 짬뽕국물',
    category: 'chinese',
    description: '센 불에 밥알 하나하나 코팅하듯 볶아낸 황금 볶음밥',
    doroQuote: '짜장 소스 살짝 얹고 짬뽕 국물 떠먹으면 극락이다 도로롱.',
    tags: ['밥류', '고소', '간편'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'c6',
    name: '바삭 꿔바로우',
    category: 'chinese',
    description: '찹쌀 피의 쫄깃함과 새콤달콤한 소스가 어우러진 북경식 탕수육',
    doroQuote: '바삭 쫀득 새콤해서 자꾸만 손이 간다 도로롱!',
    tags: ['고기', '튀김', '새콤'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'c7',
    name: '잡채밥 & 계란국',
    category: 'chinese',
    description: '탱글탱글 당면과 채소, 고기를 불향 나게 볶아 얹은 덮밥',
    doroQuote: '참기름 향 솔솔 풍기는 잡채밥 한 그릇 뚝딱이다 도로롱.',
    tags: ['밥류', '면류', '불향'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'c8',
    name: '유린기 (새콤 닭튀김)',
    category: 'chinese',
    description: '바삭한 닭튀김에 아삭한 양상추와 청양고추, 새콤 간장소스',
    doroQuote: '청양고추 팍팍 올려서 느끼함 싹 잡으라 도로롱!',
    tags: ['닭고기', '튀김', '새콤'],
    specialDoroEmotion: 'chicken',
    enabled: true,
  },
  {
    id: 'c9',
    name: '깐풍기 (매콤 닭튀김)',
    category: 'chinese',
    description: '바삭하게 튀긴 닭고기에 마늘과 고추 기름으로 볶아낸 요리',
    doroQuote: '매콤짭조름한 양념이 입에 쫙쫙 붙는다 도로롱!',
    tags: ['닭고기', '매콤', '튀김'],
    specialDoroEmotion: 'chicken',
    enabled: true,
  },
  {
    id: 'c10',
    name: '멘보샤 (새우 식빵튀김)',
    category: 'chinese',
    description: '두툼한 통새우 살을 식빵 사이에 넣고 바삭하게 튀긴 별미',
    doroQuote: '스위트 칠리소스 푹 찍어서 한입에 쏙 넣으라 도로롱!',
    tags: ['해산물', '튀김', '고급'],
    specialDoroEmotion: 'dimsum',
    enabled: true,
  },
  {
    id: 'c11',
    name: '딤섬 & 소롱포 (샤오롱바오)',
    category: 'chinese',
    description: '피를 살짝 찢어 뜨거운 육즙 먼저 마시고 생강 얹어먹기',
    doroQuote: '육즙 호로록 조심해라 도로롱! 입천장 다 데인다 도로롱!',
    tags: ['만두', '딤섬', '육즙'],
    specialDoroEmotion: 'dimsum',
    enabled: true,
  },
  {
    id: 'c12',
    name: '우육면 (대만식)',
    category: 'chinese',
    description: '큼직하고 부드러운 소고기 덩어리와 진하고 깊은 향신료 육수',
    doroQuote: '청경채랑 갓절임 곁들여서 이국적인 맛을 즐기라 도로롱!',
    tags: ['면류', '국물', '소고기'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'c13',
    name: '마파두부 덮밥',
    category: 'chinese',
    description: '부드러운 연두부와 다진 돼지고기를 매콤 칼칼한 두반장에 볶기',
    doroQuote: '얼얼한 마파두부 밥에 쓱쓱 비비면 밥도둑이다 도로롱!',
    tags: ['밥류', '매운', '두부'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'c14',
    name: '동파육 덮밥',
    category: 'chinese',
    description: '달콤 짭조름한 소스에 장시간 쪄내 입에서 녹아내리는 돼지고기',
    doroQuote: '청경채에 싸서 부드러운 고기를 입안 가득 채우라 도로롱!',
    tags: ['고기', '고급', '단짠'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'c15',
    name: '양꼬치 & 꿔바로우',
    category: 'chinese',
    description: '빙글빙글 돌아가는 화로에 구운 양꼬치와 쯔란 양념가루',
    doroQuote: '칭따오 맥주 한 잔 곁들이면 오늘 하루 피로 끝이다 도로롱!',
    tags: ['고기', '구이', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },

  // =================== 양식 (Western - 12종) ===================
  {
    id: 'w1',
    name: '베이컨 까르보나라 / 크림 파스타',
    category: 'western',
    description: '고소하고 꾸덕한 크림 소스에 노릇한 베이컨이 듬뿍',
    doroQuote: '포크로 돌돌 말아서 도로롱 입에도 한 입 넣어달라 도로롱!',
    tags: ['면류', '양식', '꾸덕'],
    specialDoroEmotion: 'pizza',
    enabled: true,
  },
  {
    id: 'w2',
    name: '매콤 해물 토마토 파스타',
    category: 'western',
    description: '신선한 홍합, 새우, 오징어와 상큼매콤 토마토 소스',
    doroQuote: '느끼하지 않고 깔끔하게 즐기는 파스타다 도로롱!',
    tags: ['면류', '해산물', '매콤'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'w3',
    name: '명란 오일 파스타 / 알리오올리오',
    category: 'western',
    description: '올리브 오일과 마늘 향, 짭조름한 명란이 톡톡 터지는 맛',
    doroQuote: '깔끔 담백하면서도 감칠맛이 폭발한다 도로롱!',
    tags: ['면류', '오일', '깔끔'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'w4',
    name: '페퍼로니 화덕 피자',
    category: 'western',
    description: '치즈가 쭉 늘어나는 갓 구운 피자에 짭짤한 페퍼로니 토핑',
    doroQuote: '치즈 늘어나는 것 좀 봐라 도로롱! 갈릭디핑소스 팍팍 찍으라 도로롱!',
    tags: ['치즈', '피자', '헤비'],
    specialDoroEmotion: 'pizza',
    enabled: true,
  },
  {
    id: 'w5',
    name: '고르곤졸라 피자 & 꿀',
    category: 'western',
    description: '진한 블루치즈 풍미에 달콤한 꿀을 푹 찍어먹는 피자',
    doroQuote: '단짠단짠 꿀 찍어 먹으면 도로롱도 춤춘다 도로롱!',
    tags: ['치즈', '피자', '달달'],
    specialDoroEmotion: 'pizza',
    enabled: true,
  },
  {
    id: 'w6',
    name: '두툼 수제버거 & 감자튀김',
    category: 'western',
    description: '육즙 터지는 소고기 패티와 멜팅 치즈, 바삭한 감튀',
    doroQuote: '입 찢어지게 크게 벌리고 앙 베어물라 도로롱!',
    tags: ['버거', '고기', '헤비'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'w7',
    name: '비프 찹스테이크 / 안심 스테이크',
    category: 'western',
    description: '겉은 바삭 속은 촉촉 미디엄 레어로 구운 소고기 스테이크',
    doroQuote: '오늘은 칼질하는 날이다 도로롱! 우아하게 썰어라 도로롱!',
    tags: ['고기', '고급', '양식'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'w8',
    name: '경양식 돈까스 & 스프',
    category: 'western',
    description: '후추 톡톡 뿌린 오뚜기 크림스프와 얇고 넓은 옛날 돈까스',
    doroQuote: '달달한 데미글라스 소스 듬뿍 적셔 밥이랑 먹으라 도로롱!',
    tags: ['튀김', '고기', '추억'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },
  {
    id: 'w9',
    name: '치즈 듬뿍 라자냐',
    category: 'western',
    description: '넓은 파스타 면과 라구 소스, 모짜렐라 치즈를 층층이 쌓아 굽기',
    doroQuote: '오븐에서 갓 나온 뜨거운 라자냐는 사랑이다 도로롱!',
    tags: ['치즈', '오븐', '양식'],
    specialDoroEmotion: 'pizza',
    enabled: true,
  },
  {
    id: 'w10',
    name: '트러플 크림 뇨끼',
    category: 'western',
    description: '쫄깃 포슬한 감자 반죽과 그윽한 트러플 향의 크림 소스',
    doroQuote: '고급스러운 트러플 향에 취해버린다 도로롱...',
    tags: ['감자', '양식', '고급'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'w11',
    name: '바베큐 폭립 플래터',
    category: 'western',
    description: '달콤한 바베큐 소스를 발라 푹 구워낸 돼지 등갈비',
    doroQuote: '양손에 쥐고 뼈째 뜯어야 제맛이다 도로롱!',
    tags: ['고기', '헤비', '푸짐'],
    specialDoroEmotion: 'fat',
    enabled: true,
  },
  {
    id: 'w12',
    name: '에그인헬 (샥슈카) & 바게트',
    category: 'western',
    description: '매콤한 토마토 소스에 반숙 달걀을 빠뜨려 바게트에 얹어먹기',
    doroQuote: '빵에 듬뿍 얹어 먹으면 브런치 느낌 제대로다 도로롱!',
    tags: ['토마토', '빵', '브런치'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },

  // =================== 분식 (Snack - 10종) ===================
  {
    id: 's1',
    name: '떡볶이 & 튀김 & 순대 (떡튀순)',
    category: 'snack',
    description: '매콤달콤 떡볶이 국물에 김말이와 찰순대 푹 찍먹',
    doroQuote: '분식 3대장 세트는 언제 먹어도 실패가 없다 도로롱!',
    tags: ['매콤', '분식', '인기', '떡볶이'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's2',
    name: '참치김밥 & 치즈라면',
    category: 'snack',
    description: '마요네즈 듬뿍 참치김밥과 노란 슬라이스 치즈 얹은 라면',
    doroQuote: '단돈 몇 천원에 누리는 극강의 가성비 행복이다 도로롱.',
    tags: ['간편', '가성비', '분식'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's3',
    name: '로제 떡볶이 & 중국당면',
    category: 'snack',
    description: '부드러운 크림과 매콤 고추장의 조화, 쫀득 쫠깃 중국당면',
    doroQuote: '소시지랑 베이컨 쏙쏙 골라먹는 재미가 쏠쏠하다 도로롱!',
    tags: ['매콤', '꾸덕', '인기', '떡볶이'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's4',
    name: '새콤달콤 쫄면 & 군만두',
    category: 'snack',
    description: '아삭한 콩나물과 양배추, 매콤 새콤 쫄깃 면발에 바삭 만두',
    doroQuote: '침샘 폭발하는 새콤한 맛에 눈이 번쩍 뜨인다 도로롱!',
    tags: ['새콤', '매콤', '쫄깃'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's5',
    name: '국물 떡볶이 & 김밥 퐁당',
    category: 'snack',
    description: '숟가락으로 국물과 떡을 함께 떠먹는 자작한 국물 떡볶이',
    doroQuote: '숟가락으로 국물이랑 같이 퍼먹어야 진리다 도로롱!',
    tags: ['국물', '매콤', '떡볶이'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's6',
    name: '라볶이 & 튀김범벅',
    category: 'snack',
    description: '라면사리가 떡볶이 양념을 흠뻑 머금은 마성의 라볶이',
    doroQuote: '면발 먼저 건져먹고 남은 국물에 삶은 계란 으깨라 도로롱!',
    tags: ['면류', '매콤', '떡볶이'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's7',
    name: '추억의 떡꼬치 & 피카츄 돈까스',
    category: 'snack',
    description: '바삭하게 튀겨 달콤 매콤 양념치킨 소스를 듬뿍 바른 간식',
    doroQuote: '하굣길 분식집 앞 추억이 방울방울 떠오른다 도로롱!',
    tags: ['간식', '추억', '달달'],
    specialDoroEmotion: 'tteokbokki',
    enabled: true,
  },
  {
    id: 's8',
    name: '부산 물떡 & 어묵 꼬치',
    category: 'snack',
    description: '뜨끈하고 시원한 멸치 무 육수에 푹 불린 가래떡과 어묵',
    doroQuote: '종이컵에 국물 따라서 호호 불며 마시라 도로롱!',
    tags: ['국물', '따뜻', '분식'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 's9',
    name: '납작만두 비빔야채',
    category: 'snack',
    description: '기름에 지진 대구식 얇은 납작만두에 매콤새콤 양배추 무침 싸먹기',
    doroQuote: '만두 피에 야채 싸서 돌돌 말아먹으면 중독된다 도로롱!',
    tags: ['만두', '새콤', '별미'],
    specialDoroEmotion: 'dimsum',
    enabled: true,
  },
  {
    id: 's10',
    name: '바삭 모둠 핫도그',
    category: 'snack',
    description: '설탕 솔솔 뿌리고 케첩과 머스터드 지그재그로 뿌린 통모짜 핫도그',
    doroQuote: '첫 입에 치즈가 쭈욱 늘어나야 제맛이다 도로롱!',
    tags: ['간식', '치즈', '달달'],
    specialDoroEmotion: 'eating',
    enabled: true,
  },

  // =================== 아시안 (Asian - 10종) ===================
  {
    id: 'a1',
    name: '양지 차돌 쌀국수 (베트남 포)',
    category: 'asian',
    description: '진한 소고기 육수에 숙주와 양파절임, 칠리소스 곁들여 먹기',
    doroQuote: '해장에도 좋고 속도 편안한 따뜻한 쌀국수다 도로롱.',
    tags: ['면류', '국물', '깔끔'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },
  {
    id: 'a2',
    name: '새우 팟타이 (태국 볶음쌀국수)',
    category: 'asian',
    description: '통통한 새우, 계란, 숙주를 땅콩분태와 달콤짭짤하게 볶기',
    doroQuote: '라임즙 쫙 뿌려 섞어 먹으면 여기가 방콕이다 도로롱!',
    tags: ['면류', '볶음', '단짠'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'a3',
    name: '나시고랭 (인도네시아 볶음밥)',
    category: 'asian',
    description: '달콤한 케찹마니스 소스로 감칠맛 폭발하게 볶아낸 세계 1위 볶음밥',
    doroQuote: '반숙 계란 노른자 톡 터뜨려 쓱쓱 비벼 먹으라 도로롱!',
    tags: ['밥류', '감칠맛', '이색'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'a4',
    name: '얼큰 새콤 똠얌꿍',
    category: 'asian',
    description: '레몬그라스 향과 매콤 새콤한 코코넛 밀크 육수의 태국 보양 수프',
    doroQuote: '처음엔 낯설어도 먹다 보면 마약처럼 빠져든다 도로롱!',
    tags: ['국물', '새콤', '이색'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'a5',
    name: '분짜 (베트남 숯불고기 국수)',
    category: 'asian',
    description: '느억맘 소스에 쌀국수 면과 숯불 돼지고기, 짜조를 푹 적셔 먹기',
    doroQuote: '새콤달콤한 소스에 푹 담가 먹으면 입맛이 확 돈다 도로롱!',
    tags: ['면류', '고기', '상큼'],
    specialDoroEmotion: 'bbq',
    enabled: true,
  },
  {
    id: 'a6',
    name: '반미 바게트 샌드위치',
    category: 'asian',
    description: '바삭한 쌀 바게트에 고기, 오이, 절임 무당근, 고수를 넣은 샌드위치',
    doroQuote: '고수 팍팍 넣어서 한 입 크게 베어물라 도로롱!',
    tags: ['샌드위치', '빵', '간편'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'a7',
    name: '푸팟퐁커리 (게살 커리)',
    category: 'asian',
    description: '부드러운 소프트쉘 크랩과 계란, 코코넛 밀크가 어우러진 태국 커리',
    doroQuote: '밥에 쓱쓱 비벼 먹으면 밥 한 공기 순삭이다 도로롱!',
    tags: ['커리', '해산물', '고급'],
    specialDoroEmotion: 'chef',
    enabled: true,
  },
  {
    id: 'a8',
    name: '인도 버터치킨 커리 & 난',
    category: 'asian',
    description: '부드럽고 크리미한 마크니 커리에 화덕에서 구운 쫄깃 갈릭난 찍먹',
    doroQuote: '갓 구운 뜨거운 난 찢어서 커리 듬뿍 찍으라 도로롱!',
    tags: ['커리', '빵', '이색'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'a9',
    name: '팟카파오무쌉 (태국 바질돼지고기덮밥)',
    category: 'asian',
    description: '다진 돼지고기를 매콤한 고추와 바질로 센 불에 볶아 올린 덮밥',
    doroQuote: '태국의 김치볶음밥 같은 소울푸드다 도로롱! 감칠맛 최고다 도로롱!',
    tags: ['밥류', '매콤', '고기'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'a10',
    name: '탄탄멘 (고소 매콤)',
    category: 'asian',
    description: '참깨/땅콩 소스의 진한 고소함과 고추기름의 매콤함이 어우러진 면',
    doroQuote: '국물이 묵직하고 고소해서 국물까지 다 마시게 된다 도로롱!',
    tags: ['면류', '국물', '고소'],
    specialDoroEmotion: 'ramen',
    enabled: true,
  },

  // =================== 패스트푸드 (Fastfood - 8종) ===================
  {
    id: 'f1',
    name: '더블 치즈버거 세트',
    category: 'fastfood',
    description: '패티 두 장, 치즈 두 장의 진한 풍미와 갓 튀긴 감자튀김',
    doroQuote: '10분 컷으로 먹고 쉬고 싶을 땐 버거가 최고다 도로롱!',
    tags: ['간편', '버거', '패스트'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'f2',
    name: '서브웨이 샌드위치 (이탈리안 비엠티)',
    category: 'fastfood',
    description: '내 입맛대로 빵과 채소, 소스를 커스텀하는 신선한 샌드위치',
    doroQuote: '소스는 스위트어니언과 렌치가 국룰이다 도로롱!',
    tags: ['신선', '간편', '샌드위치', '버거'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'f3',
    name: '멕시칸 타코 & 부리또',
    category: 'fastfood',
    description: '또띠아에 고기, 밥, 콩, 살사소스를 꽉 채워 돌돌 만 멕시칸 푸드',
    doroQuote: '나초칩 과카몰리에 푹 찍어서 같이 먹으라 도로롱!',
    tags: ['이색', '간편', '매콤'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'f4',
    name: '통다리살 치킨버거 (싸이버거 스타일)',
    category: 'fastfood',
    description: '바삭하게 튀긴 두툼한 통닭다리살 패티와 아삭한 양상추',
    doroQuote: '한 입에 다 안 들어갈 만큼 거대하다 도로롱!',
    tags: ['버거', '치킨', '바삭'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'f5',
    name: '뉴욕 칠리 핫도그 & 감튀',
    category: 'fastfood',
    description: '뽀득 소시지 위에 다진 소고기 칠리소스와 치즈를 듬뿍 얹기',
    doroQuote: '한 손에 들고 와구와구 베어물기 딱 좋다 도로롱!',
    tags: ['간편', '소시지', '미국맛'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'f6',
    name: '치킨 텐더 & 케이준 프라이',
    category: 'fastfood',
    description: '겉바속촉 순살 치킨 텐더에 허니머스터드 푹 찍먹',
    doroQuote: '손가락 쪽쪽 빨아가며 먹는 바삭 치킨이다 도로롱!',
    tags: ['치킨', '간편', '바삭'],
    specialDoroEmotion: 'chicken',
    enabled: true,
  },
  {
    id: 'f7',
    name: '터키 케밥 (치킨/비프)',
    category: 'fastfood',
    description: '불에 구운 고기와 신선한 야채를 또띠아에 만 터키식 패스트푸드',
    doroQuote: '소스가 뚝뚝 떨어질 정도로 푸짐하게 먹으라 도로롱!',
    tags: ['이색', '간편', '고기'],
    specialDoroEmotion: 'burger',
    enabled: true,
  },
  {
    id: 'f8',
    name: '조각 피자 & 시원한 탄산음료',
    category: 'fastfood',
    description: '코스트코 스타일의 거대한 한 조각 피자와 무한리필 탄산',
    doroQuote: '한 조각만 먹어도 배가 든든하게 부르다 도로롱!',
    tags: ['피자', '가성비', '헤비'],
    specialDoroEmotion: 'pizza',
    enabled: true,
  },

  // =================== 다이어트 / 가벼운 (Diet - 8종) ===================
  {
    id: 'd1',
    name: '연어 / 참치 아보카도 포케',
    category: 'diet',
    description: '현미밥 위에 신선한 깍둑썰기 연어와 채소, 스리라차마요',
    doroQuote: '다이어트도 맛있게 할 수 있다 도로롱! 도로롱도 날씬해질 테다 도로롱.',
    tags: ['건강', '가벼운', '단백질', '샐러드'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd2',
    name: '수비드 닭가슴살 샐러드',
    category: 'diet',
    description: '퍽퍽하지 않고 촉촉한 수비드 닭가슴살과 오리엔탈 드레싱',
    doroQuote: '풀때기지만 드레싱 듬뿍 뿌리면 먹을만하다 도로롱...',
    tags: ['건강', '클린', '신선', '샐러드'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd3',
    name: '리코타 치즈 샐러드 & 호밀빵',
    category: 'diet',
    description: '꾸덕한 수제 리코타 치즈와 견과류, 발사믹 글레이즈의 조화',
    doroQuote: '치즈가 고소해서 풀도 쑥쑥 넘어간다 도로롱!',
    tags: ['건강', '치즈', '가벼운', '샐러드'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd4',
    name: '월남쌈 & 샤브샤브',
    category: 'diet',
    description: '맑은 육수에 익힌 소고기와 갖가지 채소를 라이스페이퍼에 돌돌',
    doroQuote: '채소 많이 먹으니까 살 안 찐다 도로롱! (아마도)',
    tags: ['국물', '건강', '채소'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd5',
    name: '그릭 요거트 볼 (그래놀라 & 블루베리)',
    category: 'diet',
    description: '꾸덕한 그릭 요거트에 바삭한 그래놀라와 생과일, 꿀 한 스푼',
    doroQuote: '아침이나 가벼운 점심으로 속 편하게 즐기라 도로롱!',
    tags: ['가벼운', '디저트', '건강'],
    specialDoroEmotion: 'icecream',
    enabled: true,
  },
  {
    id: 'd6',
    name: '소고기 곤약 볶음밥 & 김치',
    category: 'diet',
    description: '칼로리는 낮추고 포만감은 높인 곤약쌀 볶음밥',
    doroQuote: '식단 관리 중에도 볶음밥은 포기 못 한다 도로롱!',
    tags: ['건강', '밥류', '저칼로리'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd7',
    name: '두부면 알리오올리오',
    category: 'diet',
    description: '밀가루 면 대신 담백한 두부면으로 만든 저탄수 오일 파스타',
    doroQuote: '탄수화물 줄이고 단백질 가득 채우라 도로롱!',
    tags: ['면류', '건강', '단백질'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },
  {
    id: 'd8',
    name: '계란 듬뿍 키토김밥',
    category: 'diet',
    description: '밥 대신 부드러운 지단 계란채가 가득 들어간 다이어트 김밥',
    doroQuote: '밥이 없어도 든든하고 퐁신퐁신 맛있다 도로롱!',
    tags: ['간편', '건강', '단백질'],
    specialDoroEmotion: 'salad',
    enabled: true,
  },

  // =================== 야식 / 술안주 (Night - 10종) ===================
  {
    id: 'n1',
    name: '바삭 후라이드 & 양념 반반 치킨',
    category: 'night',
    description: '겉은 바삭 속은 촉촉, 시원한 맥주를 부르는 치킨 한 마리',
    doroQuote: '치맥 한 잔이면 오늘 하루 스트레스가 싹 날아간다 도로롱!',
    tags: ['치킨', '맥주', '헤비', '야식'],
    specialDoroEmotion: 'chicken',
    enabled: true,
  },
  {
    id: 'n2',
    name: '직화 불막창 & 불닭발',
    category: 'night',
    description: '매콤한 불향이 코를 찌르고 쫄깃하게 씹히는 야식 끝판왕',
    doroQuote: '씁하씁하 매워도 멈출 수 없다 도로롱! 쿨피스랑 계란찜 필수다 도로롱!',
    tags: ['매운', '안주', '야식'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },
  {
    id: 'n3',
    name: '쫄깃 온족발 & 매콤 보쌈',
    category: 'night',
    description: '탱글탱글 콜라겐 껍질 족발과 새콤달콤 쟁반 막국수 쌈',
    doroQuote: '막국수에 족발 돌돌 말아서 한입 가득 넣으라 도로롱!',
    tags: ['고기', '야식', '푸짐', '헤비'],
    specialDoroEmotion: 'fat',
    enabled: true,
  },
  {
    id: 'n4',
    name: '얼큰 소곱창 전골',
    category: 'night',
    description: '곱이 꽉 찬 소곱창과 들깨가루, 깻잎이 뿜어내는 진국 국물',
    doroQuote: '소주를 부르는 궁극의 국물이다 도로롱 (딸꾹)!',
    tags: ['국물', '얼큰', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },
  {
    id: 'n5',
    name: '골뱅이 무침 & 소면',
    category: 'night',
    description: '새콤달콤 매콤 양념에 파채와 쫄깃 골뱅이, 참기름 소면 비비기',
    doroQuote: '소면 양념에 비벼서 골뱅이랑 싹 집어먹으라 도로롱!',
    tags: ['새콤', '매콤', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },
  {
    id: 'n6',
    name: '모둠 꼬치구이 (야키토리)',
    category: 'night',
    description: '숯불 향 입힌 닭파꼬치, 염통, 닭날개에 시원한 하이볼 한 잔',
    doroQuote: '꼬치 하나씩 쏙쏙 빼먹으며 하루를 마무리하라 도로롱!',
    tags: ['구이', '고기', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },
  {
    id: 'n7',
    name: '고소한 먹태 & 청양마요 간장',
    category: 'night',
    description: '바삭하게 구운 먹태를 마요네즈+청양고추+간장 소스에 푹 찍먹',
    doroQuote: '배부를 때 2차 안주로는 먹태가 1등이다 도로롱!',
    tags: ['가벼운', '맥주', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },
  {
    id: 'n8',
    name: '뜨끈 오뎅나베 (어묵탕)',
    category: 'night',
    description: '유부주머니와 다양한 어묵이 들어간 맑고 따뜻한 이자카야 나베',
    doroQuote: '찬 바람 불 땐 따끈한 어묵 국물에 사케 한 잔이다 도로롱.',
    tags: ['국물', '따뜻', '안주'],
    specialDoroEmotion: 'soup',
    enabled: true,
  },
  {
    id: 'n9',
    name: '치즈 감자전 & 막걸리',
    category: 'night',
    description: '감자채를 바삭하게 부치고 속에 모짜렐라 치즈를 넣은 전',
    doroQuote: '비 오는 날엔 막걸리에 전이 진리다 도로롱!',
    tags: ['치즈', '바삭', '안주'],
    specialDoroEmotion: 'beer',
    enabled: true,
  },
  {
    id: 'n10',
    name: '국물 닭발 & 주먹밥',
    category: 'night',
    description: '비닐장갑 끼고 뜯는 맵싹한 국물 닭발과 참치마요 주먹밥',
    doroQuote: '매운 양념에 주먹밥 푹 찍어 먹으면 스트레스 제로다 도로롱!',
    tags: ['매운', '야식', '안주'],
    specialDoroEmotion: 'spicy',
    enabled: true,
  },

  // =================== 디저트 / 카페 (Dessert - 10종) ===================
  {
    id: 'de1',
    name: '생명수 아이스 아메리카노 & 치즈케이크',
    category: 'dessert',
    description: '현대인의 필수 영양제 아아메와 꾸덕한 뉴욕 치즈케이크',
    doroQuote: '식후 땡은 아아메다 도로롱... 도로롱도 카페인 수혈한다 도로롱.',
    tags: ['커피', '달달', '디저트'],
    specialDoroEmotion: 'coffee',
    enabled: true,
  },
  {
    id: 'de2',
    name: '달콤 바삭 크로플 & 바닐라 아이스크림',
    category: 'dessert',
    description: '버터 풍미 가득한 크로플 위에 아이스크림과 메이플 시럽',
    doroQuote: '따뜻한 크로플에 차가운 아이스크림... 도로롱 기절한다 도로롱!',
    tags: ['달달', '빵', '디저트', '아이스크림'],
    specialDoroEmotion: 'icecream',
    enabled: true,
  },
  {
    id: 'de3',
    name: '인절미 눈꽃 팥빙수 / 망고빙수',
    category: 'dessert',
    description: '입안에서 사르르 녹는 우유 얼음 위에 달콤한 팥과 콩고물',
    doroQuote: '숟가락 들고 다 같이 퍼먹는 빙수는 언제나 최고다 도로롱!',
    tags: ['시원', '달달', '빙수', '아이스크림'],
    specialDoroEmotion: 'icecream',
    enabled: true,
  },
  {
    id: 'de4',
    name: '버터 풍미 겉바속촉 소금빵 & 라떼',
    category: 'dessert',
    description: '바닥은 버터에 튀겨지듯 바삭하고 속은 쫄깃한 소금빵',
    doroQuote: '짭조름한 펄솔트와 고소한 버터의 마법이다 도로롱!',
    tags: ['빵', '베이커리', '커피'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'de5',
    name: '타피오카 펄 흑당 버블티',
    category: 'dessert',
    description: '쫄깃쫄깃 씹히는 달콤한 타피오카 펄과 진한 밀크티',
    doroQuote: '빨대로 펄 쏙쏙 빨아들이는 손맛이 중독이다 도로롱!',
    tags: ['달달', '음료', '쫄깃'],
    specialDoroEmotion: 'coffee',
    enabled: true,
  },
  {
    id: 'de6',
    name: '갓 구운 츄러스 & 초코 디핑소스',
    category: 'dessert',
    description: '시나몬 설탕이 묻은 바삭한 츄러스를 꾸덕한 초코에 푹 찍먹',
    doroQuote: '놀이공원 온 기분 낼 수 있는 달콤한 행복이다 도로롱!',
    tags: ['달달', '빵', '디저트'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'de7',
    name: '포르투갈식 에그타르트',
    category: 'dessert',
    description: '바삭바삭 결이 살아있는 페이스트리 속에 부드러운 커스터드 크림',
    doroQuote: '따뜻할 때 한 입 베어물면 크림이 입안 가득 퍼진다 도로롱.',
    tags: ['달달', '베이커리', '디저트'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'de8',
    name: '달콤 쫀득 뚱카롱 (마카롱)',
    category: 'dessert',
    description: '쫀득한 꼬끄 사이에 두툼하고 달콤한 필링이 가득',
    doroQuote: '알록달록 예쁘고 달달해서 당 충전 직빵이다 도로롱!',
    tags: ['달달', '디저트', '간식'],
    specialDoroEmotion: 'bread',
    enabled: true,
  },
  {
    id: 'de9',
    name: '새콤달콤 생딸기 요거트 스무디',
    category: 'dessert',
    description: '진짜 딸기를 듬뿍 갈아 넣어 상큼하고 시원한 스무디',
    doroQuote: '빨간 딸기 색깔이 도로롱 머리색처럼 예쁘다 도로롱!',
    tags: ['음료', '시원', '상큼'],
    specialDoroEmotion: 'icecream',
    enabled: true,
  },
  {
    id: 'de10',
    name: '초코 퍼지 브라우니 & 바닐라 젤라또',
    category: 'dessert',
    description: '묵직하고 진한 다크초콜릿 브라우니와 쫀득한 젤라또 아이스크림',
    doroQuote: '스트레스 만땅일 땐 초코 폭탄이 정답이다 도로롱!',
    tags: ['초코', '달달', '디저트', '아이스크림'],
    specialDoroEmotion: 'icecream',
    enabled: true,
  },
];
